# Uncomment this line to define a global platform for your project

# platform :ios, '9.0'


target 'HuoBanMall' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HuoBanMall

pod 'SVProgressHUD'
pod 'BlocksKit'
pod 'iRate'
pod 'TPKeyboardAvoiding'
pod 'SDWebImage'
pod 'SSZipArchive'
pod 'MKNetworkKit'
pod 'MJRefresh'
pod 'AFNetworking'
pod 'MJExtension'
pod 'UMengAnalytics-NO-IDFA'
pod 'IQKeyboardManager'
pod 'HMQRCodeScanner'

  target 'HuoBanMallTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HuoBanMallUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
