# Uncomment this line to define a global platform for your project


target 'sdasdasdasd' do


  pod 'SHXMLParser','1.1.0'
  #pod 'ASIHTTPRequest','1.8.1'
  pod 'SSToolkit'
  pod 'ConciseKit','0.1.2'
  pod 'SVProgressHUD'
  pod 'BlocksKit','2.2.5'
  #pod 'MBProgressHUD','0.8'
  #pod 'CWPopup','1.2.4'
  pod 'iRate', '~> 1.10.3'
  #pod 'iVersion','1.11.4'
  #pod 'TPKeyboardAvoiding','1.2.3'
  #pod 'SWTableViewCell', '~> 0.3.7'
  #pod 'AFNetworking','~>2.0'
  #pod 'MMDrawerController', '~> 0.5.7'
  pod 'INTULocationManager'
  pod 'FMDB'
  pod 'SDWebImage', '~>3.7'
  pod 'PNChart'
  pod 'pop', '~> 1.0'
  pod 'RESideMenu'
  pod 'SSZipArchive'
  pod 'MKNetworkKit'
  pod 'MJRefresh'
  pod 'SSZipArchive'

  target 'sdasdasdasdTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sdasdasdasdUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
